### ISSUE TITLE
Large files

### ISSUE THREAD

**Issue by gonza-lito** [rteeter/logCollection#5]
Hi!!
Gonza from cribl here!
Thanks for working on this!

how would this solution perform with a large file say > 1GB?

https://github.com/rteeter/logCollection/blob/9bd307cd6e8f368b1208ccd47ca62d49b8a8b4fa/log-retrieval-server/src/log_retrieval_server.py#L61

**Comment by rteeter** [comment]
Hi!! Thanks for the question. Looking into this now! 👀

**Comment by rteeter** [comment]
^ PR is ready for review when you get the chance!

**Comment by gonza-lito** [comment]
Thanks for doing this! looks good!
I've sent my feedback forward!
